// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "tags": [
                    "Books"
                ],
                "summary": "Get all books",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Books"
                ],
                "summary": "Create a new book",
                "responses": {}
            }
        },
        "/books/{id}": {
            "get": {
                "tags": [
                    "Books"
                ],
                "summary": "Get a book by ID",
                "responses": {}
            },
            "put": {
                "tags": [
                    "Books"
                ],
                "summary": "Update a book",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Books"
                ],
                "summary": "Delete a book",
                "responses": {}
            }
        },
        "/ingredients": {
            "get": {
                "tags": [
                    "Ingredient"
                ],
                "summary": "Get all ingredients",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Ingredient"
                ],
                "summary": "Create a new ingredient",
                "responses": {}
            }
        },
        "/ingredients/{id}": {
            "get": {
                "tags": [
                    "Ingredient"
                ],
                "summary": "Get a ingredient by ID",
                "responses": {}
            },
            "put": {
                "tags": [
                    "Ingredient"
                ],
                "summary": "Update a ingredient",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Ingredient"
                ],
                "summary": "Delete a ingredient",
                "responses": {}
            }
        },
        "/pattern": {
            "post": {
                "description": "Detect the type of sequence and return the next number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pattern"
                ],
                "summary": "Post pattern",
                "parameters": [
                    {
                        "description": "Sequence input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.InputPattern"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/productIngredients": {
            "get": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Get all productIngredients",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Create a new productIngredient",
                "responses": {}
            }
        },
        "/productIngredients/product/{productId}": {
            "get": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Get a productIngredient by productID",
                "responses": {}
            }
        },
        "/productIngredients/{id}": {
            "get": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Get a productIngredient by ID",
                "responses": {}
            },
            "put": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Update a productIngredient",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Product Ingredient"
                ],
                "summary": "Delete a productIngredient",
                "responses": {}
            }
        },
        "/products": {
            "get": {
                "tags": [
                    "Product"
                ],
                "summary": "Get all products",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Product"
                ],
                "summary": "Create a new product",
                "responses": {}
            }
        },
        "/products/{id}": {
            "get": {
                "tags": [
                    "Product"
                ],
                "summary": "Get a product by ID",
                "responses": {}
            },
            "put": {
                "tags": [
                    "Product"
                ],
                "summary": "Update a product",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "Product"
                ],
                "summary": "Delete a product",
                "responses": {}
            }
        }
    },
    "definitions": {
        "handlers.InputPattern": {
            "type": "object",
            "properties": {
                "seq": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
